deps.core.mcVersion=26.1.2
deps.core.maxMcVersion=26.1.2

deps.fabric_api=0.155.2+26.1.2
deps.api.architectury=20.0.12
deps.resourcefulconfig_version=26.1:4.0.1
deps.modmenu_version=18.0.0
deps.skyblock_api_version=4.2.22
deps.skyblock_api_platform=26.1
deps.skyblocker_version=6.5.3+26.1.2
deps.owo_version=0.13.1+26.1
deps.hypixel_mod_api_version=1.0.2+build.1+mc26.1

loom.platform=fabric