deps.core.mcVersion=1.21.11
deps.core.maxMcVersion=1.21.11

deps.fabric_api=0.141.2+1.21.11
deps.api.architectury=13.0.6
deps.resourcefulconfig_version=1.21.11:3.11.3
deps.modmenu_version=13.0.3
deps.skyblock_api_version=4.1.3
deps.skyblock_api_platform=1.21.11
deps.skyblocker_version=6.0.0-beta.2+1.21.11
deps.owo_version=0.13.0+1.21.11
deps.hypixel_mod_api_version=1.0.1+build.1+mc1.21

loom.platform=fabric